#!/usr/bin/env bash

# Allow running via `zsh script.sh` (or any non-bash shell) by re-executing under bash.
# This script is not meant to be sourced.
if [ -n "${BASH_VERSION-}" ]; then
  if [ "${BASH_SOURCE[0]}" != "$0" ]; then
    echo "ERROR: Do not source this script. Run it: ./script.sh [args]" >&2
    return 1
  fi
elif [ -n "${ZSH_VERSION-}" ]; then
  case "${ZSH_EVAL_CONTEXT-}" in
    *:file)
      echo "ERROR: Do not source this script. Run it: ./script.sh [args]" >&2
      return 1
      ;;
  esac
fi
if [ -z "${BASH_VERSION-}" ]; then
  # Preserve the user's login shell hint for the tmux launcher.
  if [ -z "${OP3_PARENT_SHELL-}" ] && [ -n "${SHELL-}" ]; then
    OP3_PARENT_SHELL="${SHELL##*/}"
    export OP3_PARENT_SHELL
  fi
  if command -v bash >/dev/null 2>&1; then
    exec bash "$0" "$@"
  fi
  echo "ERROR: bash is required to run this script." >&2
  exit 1
fi

set -euo pipefail

# Preserve the user's login shell hint for the tmux launcher even when invoked via shebang.
if [[ -z "${OP3_PARENT_SHELL:-}" && -n "${SHELL:-}" ]]; then
  export OP3_PARENT_SHELL="${SHELL##*/}"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/op3_tmux/main.sh"

# -----------------------------
# Safe enum-style menu handling
# -----------------------------

# Canonical enum IDs (stable, safe for case/esac)
readonly M_LAUNCH_PICKER="launch_picker"
readonly M_BUILD="build"
readonly M_DOCTOR="doctor"
readonly M_INSTALL_DEPS="install_deps"
readonly M_ROS_ENV="ros_env"
readonly M_DOCKER_BUILD="docker_build"
readonly M_DOCKER_RUN="docker_run"
readonly M_DOCKER_COMPOSE_UP="docker_compose_up"
readonly M_DOCKER_STOP="docker_stop"
readonly M_EXIT_TMUX="exit_tmux"
readonly M_QUIT="quit"

# Order matters (Launch picker first)
readonly MENU_ENUMS=(
  "$M_LAUNCH_PICKER"
  "$M_BUILD"
  "$M_DOCTOR"
  "$M_INSTALL_DEPS"
  "$M_ROS_ENV"
  "$M_DOCKER_BUILD"
  "$M_DOCKER_RUN"
  "$M_DOCKER_COMPOSE_UP"
  "$M_DOCKER_STOP"
  "$M_EXIT_TMUX"
  "$M_QUIT"
)

# Pretty label (no numbering here)
menu_label() {
  case "$1" in
    "$M_LAUNCH_PICKER") echo "Launch picker" ;;
    "$M_BUILD")         echo "Build workspace" ;;
    "$M_DOCTOR")        echo "Health check" ;;
    "$M_INSTALL_DEPS")  echo "Install deps" ;;
    "$M_ROS_ENV")       echo "Set ROS env" ;;
    "$M_DOCKER_BUILD")  echo " Docker build" ;;
    "$M_DOCKER_RUN")    echo "Docker run (container)" ;;
    "$M_DOCKER_COMPOSE_UP") echo "Docker compose up" ;;
    "$M_DOCKER_STOP")   echo "Docker compose down" ;;
    "$M_EXIT_TMUX")     echo "Exit tmux session" ;;
    "$M_QUIT")          echo "Quit" ;;
    *)                  echo "Unknown" ;;
  esac
}

# Emoji per enum (ASCII-safe fallback: leave empty if you want)
menu_emoji() {
  case "$1" in
    "$M_LAUNCH_PICKER") echo "🚀" ;;
    "$M_BUILD")         echo "🔧" ;;
    "$M_DOCTOR")        echo "🩺" ;;
    "$M_INSTALL_DEPS")  echo "📦" ;;
    "$M_ROS_ENV")       echo "🌐" ;;
    "$M_DOCKER_BUILD")  echo "🏗️" ;;
    "$M_DOCKER_RUN")    echo "🐳" ;;
    "$M_DOCKER_COMPOSE_UP") echo "🐳" ;;
    "$M_DOCKER_STOP")   echo "🛑" ;;
    "$M_EXIT_TMUX")     echo "🧹" ;;
    "$M_QUIT")          echo "👋" ;;
    *)                  echo "" ;;
  esac
}

# Build the exact display string for gum (numbered + emoji + label)
menu_item() {
  local idx="$1"
  local id="$2"
  local emoji label
  emoji="$(menu_emoji "$id")"
  label="$(menu_label "$id")"
  printf '%2d) %s %s' "$idx" "$emoji" "$label"
}

# Convert gum selection -> enum id (robust against numbering/emojis/spacing)
choice_to_enum() {
  local picked="$1"
  # Strip leading number bullets like " 1) " / "01.) " etc
  picked="$(printf '%s' "$picked" | sed -E 's/^[[:space:]]*[0-9]+[[:space:]]*[\)\.:-]*[[:space:]]*//')"
  # Remove leading emoji-ish token (best-effort): first "word" if it contains non-alnum
  # (Keeps it simple; labels are the real source of truth.)
  picked="$(printf '%s' "$picked" | sed -E 's/^[^[:alnum:]]+[[:space:]]+//')"

  case "$picked" in
    "Launch picker")     echo "$M_LAUNCH_PICKER" ;;
    "Build workspace")   echo "$M_BUILD" ;;
    "Health check")      echo "$M_DOCTOR" ;;
    "Install deps")      echo "$M_INSTALL_DEPS" ;;
    "Set ROS env")       echo "$M_ROS_ENV" ;;
    "Docker build")      echo "$M_DOCKER_BUILD" ;;
    "Docker run (container)") echo "$M_DOCKER_RUN" ;;
    "Docker compose up") echo "$M_DOCKER_COMPOSE_UP" ;;
    "Docker compose down") echo "$M_DOCKER_STOP" ;;
    "Exit tmux session") echo "$M_EXIT_TMUX" ;;
    "Quit")              echo "$M_QUIT" ;;
    *)                   echo "$M_QUIT" ;;
  esac
}

escape_single_quotes() {
  printf "%s" "$1" | sed "s/'/'\\\\''/g"
}

persist_pref_var() {
  local key="$1"
  local value="${2-}"
  local file
  file="$(prefs_file_path)"
  mkdir -p "$(dirname "$file")" 2>/dev/null || return 0
  local tmp="${file}.tmp.$$"
  if [[ -f "$file" ]]; then
    sed -E "/^${key}=/d" "$file" > "$tmp" 2>/dev/null || : 
  else
    cat >"$tmp" <<'EOF'
# Generated by OP3 stack launcher.
# You can edit or delete this file to re-prompt.
EOF
  fi
  if [[ -n "$value" ]]; then
    local escaped
    escaped="$(escape_single_quotes "$value")"
    printf "%s='%s'\n" "$key" "$escaped" >> "$tmp"
  fi
  chmod 600 "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$file" 2>/dev/null || rm -f "$tmp" 2>/dev/null || true
}

action_default_path() {
  echo "$WS/src/ROBOTIS-OP3/op3_action_module/data/motion_custom.bin"
}

action_picker_root() {
  if [[ -d "/ros2_ws" ]]; then
    echo "/ros2_ws"
  else
    echo "$WS"
  fi
}

set_action_file() {
  local file="$1"
  [[ -z "$file" ]] && return 0
  export OP3_ACTION_FILE="$file"
  persist_pref_var "OP3_ACTION_FILE" "$file"
  echo "OP3_ACTION_FILE set to ${file}"
}

# If args provided, pass through (unchanged behavior)
if [[ $# -gt 0 ]]; then
  op3_tmux_main "$@"
  exit $?
fi

if ! command -v gum >/dev/null 2>&1; then
  echo "gum is not installed."
  cat <<'EOF'
Install with:
  sudo mkdir -p /etc/apt/keyrings
  curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
  echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
  sudo apt update && sudo apt install gum
EOF
  if [[ -t 0 && -t 1 ]]; then
    read -r -p "Install gum now? [y/N] " reply
    case "$reply" in
      y|Y|yes|YES)
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
        echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
        sudo apt update && sudo apt install gum
        ;;
    esac
  fi
  command -v gum >/dev/null 2>&1 || exit 1
fi

# Build numbered menu items (single source of truth = MENU_ENUMS)
menu_items=()
i=1
for id in "${MENU_ENUMS[@]}"; do
  menu_items+=("$(menu_item "$i" "$id")")
  i=$((i + 1))
done

while true; do
  banner

  picked="$(gum choose --header "OP3 Workspace Menu" "${menu_items[@]}")"
  action="$(choice_to_enum "$picked")"

  case "$action" in
    "$M_LAUNCH_PICKER")
      op3_tmux_main
      rc=$?
      if [[ $rc -eq 2 ]]; then
        continue
      fi
      exit $rc
      ;;

    "$M_BUILD")
      op3_tmux_main --build
      ;;

    "$M_DOCTOR")
      op3_tmux_main --doctor
      ;;

    "$M_INSTALL_DEPS")
      op3_tmux_main --install-deps
      ;;

    "$M_ROS_ENV")
      current_domain="${ROS_DOMAIN_ID:-}"
      default_domain="${ROS_DOMAIN_ID_DEFAULT:-0}"
      echo "Current ROS_DOMAIN_ID: ${current_domain:-<default ${default_domain}>}"
      domain_value="$(gum input --prompt "ROS_DOMAIN_ID (blank = default ${default_domain}): " --value "$current_domain")"
      if [[ -z "$domain_value" ]]; then
        unset ROS_DOMAIN_ID
        echo "ROS_DOMAIN_ID unset (using default ${default_domain})"
      elif [[ "$domain_value" =~ ^[0-9]+$ ]]; then
        export ROS_DOMAIN_ID="$domain_value"
        echo "ROS_DOMAIN_ID set to ${domain_value}"
      else
        echo "Invalid ROS_DOMAIN_ID: $domain_value"
      fi
      localhost_current="${ROS_LOCALHOST_ONLY:-unset}"
      localhost_choice="$(gum choose --header "ROS_LOCALHOST_ONLY (isolate DDS to localhost)" \
        "Keep (${localhost_current})" \
        "Enable (1)" \
        "Disable (0)")"
      case "$localhost_choice" in
        "Enable (1)") export ROS_LOCALHOST_ONLY="1"; echo "ROS_LOCALHOST_ONLY=1" ;;
        "Disable (0)") export ROS_LOCALHOST_ONLY="0"; echo "ROS_LOCALHOST_ONLY=0" ;;
        *) ;;
      esac

      action_default="$(action_default_path)"
      if [[ -n "${OP3_ACTION_FILE:-}" ]]; then
        echo "Current OP3_ACTION_FILE: ${OP3_ACTION_FILE}"
      else
        echo "Current OP3_ACTION_FILE: <default ${action_default}>"
      fi

      action_dir="$WS/src/ROBOTIS-OP3/op3_action_module/data"
      action_choices=()
      if [[ -d "$action_dir" ]]; then
        while IFS= read -r -d '' f; do
          action_choices+=("$f")
        done < <(find "$action_dir" -maxdepth 1 -type f -name "*.bin" -print0 | sort -z)
      fi
      action_choices+=("Browse (gum file)" "Custom path..." "Unset (use default)")

      if picked_action="$(gum choose --header "Select OP3 action file" "${action_choices[@]}")"; then
        case "$picked_action" in
          "Browse (gum file)")
            start_dir="$(action_picker_root)"
            picked_path="$(gum file "$start_dir")" || picked_path=""
            set_action_file "$picked_path"
            ;;
          "Custom path...")
            picked_path="$(gum input --prompt "OP3_ACTION_FILE path: " --value "${OP3_ACTION_FILE:-}")"
            set_action_file "$picked_path"
            ;;
          "Unset (use default)")
            unset OP3_ACTION_FILE
            persist_pref_var "OP3_ACTION_FILE" ""
            echo "OP3_ACTION_FILE unset (default ${action_default})"
            ;;
          *)
            set_action_file "$picked_action"
            ;;
        esac
      else
        echo "OP3_ACTION_FILE unchanged."
      fi
      ;;

    "$M_DOCKER_BUILD")
      tag="$(gum input --value "${OP3_DOCKER_TAG:-op3-webots-ros2:humble}" --prompt "Image tag: ")"
      with_webots=1
      webots_version="${OP3_DOCKER_WEBOTS_VERSION:-R2025a}"
      webots_prefix="${OP3_DOCKER_WEBOTS_PACKAGE_PREFIX:-}"
      gum confirm "Include Webots?" && with_webots=1 || with_webots=0
      if [[ "$with_webots" -eq 1 ]]; then
        webots_version="$(gum input --value "$webots_version" --prompt "Webots version: ")"
        webots_prefix="$(gum input --value "$webots_prefix" --prompt "Webots package prefix (optional): ")"
      fi
      OP3_DOCKER_TAG="$tag" OP3_DOCKER_WITH_WEBOTS="$with_webots" \
        OP3_DOCKER_WEBOTS_VERSION="$webots_version" \
        OP3_DOCKER_WEBOTS_PACKAGE_PREFIX="$webots_prefix" \
        op3_tmux_main --docker-build
      ;;

    "$M_DOCKER_RUN")
      run_flags=""
      gum confirm "Run in detached mode?" && run_flags="-d"
      mount_choice="$(gum choose --header "Mount mode" \
        "Cache (src read-only + build/install/log)" \
        "Src only (read-only)" \
        "Full workspace (read/write)" \
        "No mounts (sandbox)")"
      mount_mode="cache"
      case "$mount_choice" in
        "Cache (src read-only + build/install/log)") mount_mode="cache" ;;
        "Src only (read-only)") mount_mode="src" ;;
        "Full workspace (read/write)") mount_mode="full" ;;
        "No mounts (sandbox)") mount_mode="none" ;;
      esac
      src_ro="1"
      if [[ "$mount_mode" == "src" || "$mount_mode" == "cache" ]]; then
        src_choice="$(gum choose --header "Src mount access" \
          "Read-only (safer)" \
          "Read/write")"
        [[ "$src_choice" == "Read/write" ]] && src_ro="0"
      fi
      OP3_DOCKER_RUN_FLAGS="$run_flags" \
        OP3_DOCKER_MOUNT_MODE="$mount_mode" \
        OP3_DOCKER_SRC_RO="$src_ro" \
        op3_tmux_main --docker-run
      ;;

    "$M_DOCKER_COMPOSE_UP")
      up_flags=""
      gum confirm "Run in detached mode?" && up_flags="-d"
      gum confirm "Build before run?" && up_flags="--build $up_flags"
      OP3_DOCKER_UP_FLAGS="$up_flags" op3_tmux_main --docker-up
      ;;

    "$M_DOCKER_STOP")
      op3_tmux_main --docker-down
      ;;

    "$M_EXIT_TMUX")
      op3_tmux_main --exit
      exit $?
      ;;

    "$M_QUIT"|*)
      exit 0
      ;;
  esac
done
