yolo_detector:
  ros__parameters:
    image_topic: /robotis_op3/camera/image_raw
    ball_center_topic: /vision/yolo/ball_center
    model_path: models/yolo.onnx
    use_gpu: false
    use_fp16: false
    dnn_backend: opencv
    dnn_target: cpu
    device: CPU
    input_size: 640
    ball_confidence_threshold: 0.5
    goalpost_confidence_threshold: 0.5
    robot_confidence_threshold: 0.5
    intersection_confidence_threshold: 0.4
    nms_threshold: 0.5
    nms_score_threshold: 0.1
    publish_debug: true
    frame_skip: 1
