has_tmux() { command -v tmux >/dev/null 2>&1; }
has_ros2() { command -v ros2 >/dev/null 2>&1; }
has_cmd() { command -v "$1" >/dev/null 2>&1; }

ensure_tmux_installed() {
  if has_tmux; then
    return 0
  fi
  echo "${YLW}tmux is not installed.${RST}" >&2
  cat <<'EOF' >&2
Install with:
  sudo apt install tmux
EOF
  if [[ -t 0 && -t 1 ]]; then
    read -r -p "Install tmux now? [y/N] " reply
    case "$reply" in
      y|Y|yes|YES)
        sudo apt install tmux
        ;;
    esac
  fi
  has_tmux || die "tmux is not installed. Please install it and retry."
}

prefer_zsh_shell() {
  [[ "${OP3_PREFER_ZSH:-0}" == "1" ]] && return 0
  [[ "${OP3_PARENT_SHELL:-}" == "zsh" ]] && return 0
  [[ "${SHELL:-}" == *zsh ]] && return 0
  return 1
}

prefs_file_path() {
  if [[ -n "${OP3_PREFS_FILE:-}" ]]; then
    echo "$OP3_PREFS_FILE"
    return 0
  fi
  echo "${OP3_CONFIG_DIR:-${HOME}/.config/op3-stack}/prefs.sh"
}

save_shell_preference() {
  local runner="$1"
  local prefer_zsh="$2"

  local file
  file="$(prefs_file_path)"
  mkdir -p "$(dirname "$file")" 2>/dev/null || return 0

  local tmp="${file}.tmp.$$"
  cat >"$tmp" 2>/dev/null <<EOF
# Generated by OP3 stack launcher.
# You can edit or delete this file to re-prompt.
OP3_SHELL_RUNNER='${runner}'
OP3_PREFER_ZSH=${prefer_zsh}
EOF
  chmod 600 "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$file" 2>/dev/null || rm -f "$tmp" 2>/dev/null || true
}

maybe_prompt_shell_preference() {
  # Prompt once (first run) if gum is available and we're in a TTY.
  [[ "${OP3_ASK_SHELL_PREFERENCE:-1}" == "1" ]] || return 0
  [[ -t 0 && -t 1 ]] || return 0
  command -v gum >/dev/null 2>&1 || return 0

  local file
  file="$(prefs_file_path)"
  [[ -f "$file" ]] && return 0

  local choice
  choice="$(gum choose --header "Pick shell for tmux panes (saved as preference)" "zsh" "bash")" || return 0
  case "$choice" in
    zsh)
      OP3_SHELL_RUNNER="zsh -lc"
      OP3_PREFER_ZSH=1
      ;;
    bash)
      OP3_SHELL_RUNNER="bash -lc"
      OP3_PREFER_ZSH=0
      ;;
    *)
      return 0
      ;;
  esac

  export OP3_SHELL_RUNNER OP3_PREFER_ZSH
  save_shell_preference "$OP3_SHELL_RUNNER" "$OP3_PREFER_ZSH"
  SHELL_RUNNER="$OP3_SHELL_RUNNER"
}

webots_available() {
  if [[ -n "${WEBOTS_HOME:-}" ]]; then
    [[ -d "$WEBOTS_HOME" ]] && return 0
    [[ -x "$WEBOTS_HOME" ]] && return 0
  fi
  command -v webots >/dev/null 2>&1 && return 0
  command -v webots-bin >/dev/null 2>&1 && return 0
  return 1
}

detect_setup_optional() {
  if [[ -n "${SETUP:-}" ]]; then
    [[ -f "$SETUP" ]] && return 0
    return 1
  fi

  # Prefer bash/sh setup scripts since the project entrypoint is bash. Use zsh
  # only if explicitly requested via --setup/OP3_SETUP or OP3_SHELL_RUNNER.
  local cand1 cand2 cand3 cand4 cand5 cand6
  if prefer_zsh_shell; then
    cand1="$WS/install/setup.zsh"
    cand2="$WS/install/setup.bash"
    cand3="$WS/install/setup.sh"
    cand4="$WS/install/local_setup.zsh"
    cand5="$WS/install/local_setup.bash"
    cand6="$WS/install/local_setup.sh"
  else
    cand1="$WS/install/setup.bash"
    cand2="$WS/install/setup.sh"
    cand3="$WS/install/setup.zsh"
    cand4="$WS/install/local_setup.bash"
    cand5="$WS/install/local_setup.sh"
    cand6="$WS/install/local_setup.zsh"
  fi

  for c in "$cand1" "$cand2" "$cand3" "$cand4" "$cand5" "$cand6"; do
    if [[ -f "$c" ]]; then
      SETUP="$c"
      return 0
    fi
  done
  return 1
}

check_ros_pkg() {
  local pkg="$1"
  if [[ -z "${SETUP:-}" ]]; then
    return 1
  fi
  $SHELL_RUNNER "source '$SETUP'; ros2 pkg prefix $pkg >/dev/null 2>&1"
}

ensure_webots_bin() {
  if [[ -n "${WEBOTS_HOME:-}" ]]; then
    [[ -x "$WEBOTS_HOME" ]] || die "WEBOTS_HOME is set but not executable: $WEBOTS_HOME"
    return 0
  fi

  if command -v webots >/dev/null 2>&1; then
    return 0
  fi
  if command -v webots-bin >/dev/null 2>&1; then
    return 0
  fi

  die "Webots binary not found. Install Webots or set WEBOTS_HOME to the executable path."
}

auto_detect_setup() {
  if [[ -n "$SETUP" ]]; then
    [[ -f "$SETUP" ]] || die "Setup file not found: $SETUP"
    return 0
  fi

  # Prefer bash/sh setup scripts since the project entrypoint is bash.
  local cand1 cand2 cand3 cand4 cand5 cand6
  if prefer_zsh_shell; then
    cand1="$WS/install/setup.zsh"
    cand2="$WS/install/setup.bash"
    cand3="$WS/install/setup.sh"
    cand4="$WS/install/local_setup.zsh"
    cand5="$WS/install/local_setup.bash"
    cand6="$WS/install/local_setup.sh"
  else
    cand1="$WS/install/setup.bash"
    cand2="$WS/install/setup.sh"
    cand3="$WS/install/setup.zsh"
    cand4="$WS/install/local_setup.bash"
    cand5="$WS/install/local_setup.sh"
    cand6="$WS/install/local_setup.zsh"
  fi

  for c in "$cand1" "$cand2" "$cand3" "$cand4" "$cand5" "$cand6"; do
    if [[ -f "$c" ]]; then
      SETUP="$c"
      return 0
    fi
  done

  die "Could not auto-detect setup file in $WS/install/. Set OP3_SETUP or use --setup PATH."
}

prefer_bash_setup() {
  if [[ "$SETUP" != *.zsh ]]; then
    return 1
  fi
  local alt_bash="${SETUP%.zsh}.bash"
  local alt_sh="${SETUP%.zsh}.sh"
  if [[ -f "$alt_bash" ]]; then
    SETUP="$alt_bash"
    return 0
  fi
  if [[ -f "$alt_sh" ]]; then
    SETUP="$alt_sh"
    return 0
  fi
  return 1
}

auto_detect_shell_runner() {
  if [[ -z "${OP3_SHELL_RUNNER:-}" && -z "${SHELL_RUNNER:-}" ]]; then
    maybe_prompt_shell_preference
  fi

  if [[ -n "$SHELL_RUNNER" ]]; then
    # If the user forces zsh, fail fast with a clearer message.
    if [[ "$SHELL_RUNNER" == zsh* ]] && ! command -v zsh >/dev/null 2>&1; then
      if prefer_bash_setup; then
        SHELL_RUNNER="bash -lc"
        return 0
      fi
      die "OP3_SHELL_RUNNER is set to zsh but zsh is not installed. Install zsh or set OP3_SHELL_RUNNER='bash -lc'."
    fi

    # Keep setup script extension aligned with the forced shell runner when possible.
    if [[ "$SHELL_RUNNER" == zsh* ]]; then
      if [[ "$SETUP" != *.zsh ]]; then
        local alt_zsh="${SETUP%.*}.zsh"
        [[ -f "$alt_zsh" ]] && SETUP="$alt_zsh"
      fi
    else
      prefer_bash_setup >/dev/null 2>&1 || true
    fi
    return 0
  fi

  if [[ "$SETUP" == *.zsh ]]; then
    if prefer_zsh_shell && command -v zsh >/dev/null 2>&1; then
      SHELL_RUNNER="zsh -lc"
      return 0
    fi

    # Prefer bash/sh setup script when not running zsh.
    if prefer_bash_setup; then
      SHELL_RUNNER="bash -lc"
      return 0
    fi

    if command -v zsh >/dev/null 2>&1; then
      SHELL_RUNNER="zsh -lc"
      return 0
    fi

    die "Setup script is zsh-only ($SETUP) but zsh is not installed. Use --setup '$WS/install/setup.bash' or install zsh."
  fi

  SHELL_RUNNER="bash -lc"
}

health_check() {
  local require_webots="${1:-1}"
  ensure_tmux_installed
  has_ros2 || die "ros2 is not installed or not in PATH."

  auto_detect_setup
  auto_detect_shell_runner
  [[ -f "$SETUP" ]] || die "Setup file not found: $SETUP"
  if [[ "$require_webots" -eq 1 ]]; then
    ensure_webots_bin
  fi

  if ! $SHELL_RUNNER "source '$SETUP'; ros2 pkg prefix op3_joy_teleop >/dev/null 2>&1"; then
    echo "${RED}ERROR:${RST} Workspace is not built/installed (missing op3_joy_teleop)." >&2
    echo "${DIM}Try:${RST} colcon build --packages-select op3_joy_teleop" >&2
    echo "${DIM}Then:${RST} source install/setup.bash" >&2
    exit 1
  fi
}

doctor_check() {
  local ok=1

  if has_tmux; then
    echo "${GRN}OK:${RST} tmux"
  else
    echo "${YLW}WARN:${RST} tmux not found"
    ok=0
  fi

  if has_ros2; then
    echo "${GRN}OK:${RST} ros2"
  else
    echo "${YLW}WARN:${RST} ros2 not found in PATH"
    ok=0
  fi

  if has_cmd colcon; then
    echo "${GRN}OK:${RST} colcon"
  else
    echo "${YLW}WARN:${RST} colcon not found (install python3-colcon-common-extensions)"
    ok=0
  fi

  if has_cmd rosdep; then
    echo "${GRN}OK:${RST} rosdep"
  else
    echo "${YLW}WARN:${RST} rosdep not found (install python3-rosdep)"
    ok=0
  fi

  if has_cmd gum; then
    echo "${GRN}OK:${RST} gum"
  else
    echo "${YLW}WARN:${RST} gum not found (install gum for menus)"
    ok=0
  fi

  if has_cmd ttyd; then
    echo "${GRN}OK:${RST} ttyd (web terminal)"
  else
    echo "${YLW}WARN:${RST} ttyd not found (install for web terminal support)"
    ok=0
  fi

  if has_cmd docker; then
    echo "${GRN}OK:${RST} docker"
  else
    echo "${YLW}WARN:${RST} docker not found (install Docker for container workflows)"
  fi

  if webots_available; then
    echo "${GRN}OK:${RST} Webots"
  else
    echo "${YLW}WARN:${RST} Webots not found (install or set WEBOTS_HOME)"
    ok=0
  fi

  if detect_setup_optional; then
    auto_detect_shell_runner
    echo "${GRN}OK:${RST} setup: $SETUP"
    if $SHELL_RUNNER "source '$SETUP'; ros2 pkg prefix op3_joy_teleop >/dev/null 2>&1"; then
      echo "${GRN}OK:${RST} workspace install (op3_joy_teleop)"
    else
      echo "${YLW}WARN:${RST} workspace not built (missing op3_joy_teleop)"
      ok=0
    fi

    local ros_pkgs=(
      rosbridge_server
      octomap_ros
      octomap_msgs
      octomap_server
      webots_ros2_driver
      foxglove_bridge
      joy
    )
    for pkg in "${ros_pkgs[@]}"; do
      if check_ros_pkg "$pkg"; then
        echo "${GRN}OK:${RST} ros2 pkg $pkg"
      else
        echo "${YLW}WARN:${RST} ros2 pkg $pkg missing"
        ok=0
      fi
    done
  else
    echo "${YLW}WARN:${RST} setup not found in $WS/install (build first)"
    ok=0
  fi

  if [[ "$ok" -eq 1 ]]; then
    echo "${GRN}Doctor:${RST} all checks passed."
    return 0
  fi

  echo "${YLW}Doctor:${RST} issues found. Run --install-deps or build."
  return 1
}
